### PR TITLE
convert chapter 01 to slides

### PR DESCRIPTION
**Pull request by laurafitzgerald**
@ciaranRoche @JameelB I tested out the [convert to slides](https://github.com/partageit/markdown-to-slides) thing.
Seems to work well. Thinking we can convert them as they are initially and then do any cleanup.

Some of the slides are bigger than the slide itself. We can split those out by adding `---` anywhere we want a break and the tool will split it.

To generate this file I ran `markdown-to-slides 01-commits.md -d true -o 01-commits.html`

Let me know if this will work and I'll go ahead and do the rest. 👍

### CODE REVIEW

**Comment by ciaranRoche** [comment]
@laurafitzgerald do you have an example of what the slides look like?

**Comment by laurafitzgerald** [comment]
You can see it if you open the html page in your browser.

**Comment by laurafitzgerald** [comment]
If we can get the RedHat Red rgb we could change it too. :D

**Comment by laurafitzgerald** [comment]
Closing, as per discussion we'll go with google slides. 👍

**Pull request closed without merging**
